FCVBuyingWebApp/Controllers/BuyingDocumentsController.cs
using FCVBuyingWebApp.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FCVBuyingWebApp.Controllers
{
    [Authorize(Roles = "Admin,Buyer")]
    public class BuyingDocumentsController : Controller
    {
        // GET: BuyingDocuments
        public ActionResult Index()
        {
            var list = Helper.BuyingDocumentHelper.GetByTW(user_setting.Crop.Crop1)
                .Where(x => x.RequestFinishStatus == true)
                .OrderByDescending(x => x.FinishStatus)
                .ThenByDescending(x => x.StationCode)
                .ThenByDescending(x => x.BuyingDocumentCode);

            return View(list);
        }
    }
}

FCVBuyingWebApp/Controllers/BuyingsController.cs
using FCVBuyingBL;
using FCVBuyingEntities;
using FCVBuyingWebApp.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FCVBuyingWebApp.Controllers
{
    [Authorize(Roles = "Admin,Buyer")]
    public class BuyingsController : Controller
    {
        // GET: Buyings
        public ActionResult Index(short crop, string stationCode,
            string farmerCode, short documentNumber)
        {
            ViewBag.BuyingDocument = Helper.BuyingDocumentHelper
                .GetSingle(crop, farmerCode, stationCode, documentNumber);

            return View(Helper.BuyingHelper
                .GetBuyingDetailByDocument(crop,
                farmerCode,
                stationCode,
                documentNumber));
        }

        [HttpPost]
        public ActionResult Index(string status, short crop, string stationCode,
            string farmerCode, short documentNumber)
        {
            if (status == "Finish")
            {
                BusinessLayerService.BuyingDocumentBL()
                    .Finish(new BuyingDocument
                    {
                        Crop = crop,
                        FarmerCode = farmerCode,
                        StationCode = stationCode,
                        DocumentNumber = documentNumber
                    });
            }
            else
            {
                BusinessLayerService.BuyingDocumentBL()
                    .UnFinish(new BuyingDocument
                    {
                        Crop = crop,
                        FarmerCode = farmerCode,
                        StationCode = stationCode,
                        DocumentNumber = documentNumber
                    });
            }

            return RedirectToAction("Index", new
            {
                crop = crop,
                stationCode = stationCode,
                farmerCode = farmerCode,
                documentNumber = documentNumber
            });
        }
    }
}

FCVBuyingWebApp/Views/BuyingDocuments/Index.cshtml
@model IEnumerable<FCVBuyingWebApp.Model.vm_BuyingDocument>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function (e) {
        var table = $("#documentTable").DataTable({
            "order": [[0, "asc"]]
        });
    });
</script>
<header class="pb-3 mb-4 border-bottom">
    <a href="#" class="d-flex align-items-center text-dark text-decoration-none">
        <span class="fs-4">Buying Document</span>
    </a>
</header>

<div class="table-responsive">
    <table class="table table-sm"
           id="documentTable">
        <thead>
            <tr>
                <th>

                </th>
                @*<th>
                        Station
                    </th>*@
                <th>
                    Curer
                </th>
                <th>
                    Doc No.
                </th>
                <th>
                    Date
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderByDescending(x => x.FinishStatus))
            {
                <tr>
                    <td>
                        <a href="@Url.Action("Index", "Buyings", new
                                {
                                    crop = item.Crop,
                                    stationCode = item.StationCode,
                                    farmerCode = item.FarmerCode,
                                    documentNumber = item.DocumentNumber
                                })">
                            <span class="btn btn-outline-secondary btn-sm"><i class="fas fa-search"></i></span>
                        </a>

                    </td>
                    @*<td>
                            @item.StationCode
                        </td>*@
                    <td>
                        @item.ExtensionAgentCode
                    </td>
                    <td>
                        @item.DocumentNumber
                    </td>
                    <td>
                        @item.CreateDate.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @{
                            if (item.FinishStatus)
                            {
                                <i class="fas fa-check-square text-success"></i>
                            }
                            else
                            {
                                <i class="fas fa-times-circle text-danger"></i>
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>