FCVBuyingWebApp/Controllers/BuyingDocumentsController.cs
using FCVBuyingWebApp.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FCVBuyingWebApp.Controllers
{
    [Authorize(Roles = "Admin,Buyer")]
    public class BuyingDocumentsController : Controller
    {
        // GET: BuyingDocuments
        public ActionResult Index()
        {
            var list = Helper.BuyingDocumentHelper.GetByTW(user_setting.Crop.Crop1)
                .Where(x => x.RequestFinishStatus == true)
                .OrderByDescending(x => x.FinishStatus)
                .ThenByDescending(x => x.StationCode)
                .ThenByDescending(x => x.BuyingDocumentCode);

            return View(list);
        }
    }
}

FCVBuyingWebApp/Controllers/NPIBuyingController.cs
using FCVBuyingBL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FCVBuyingWebApp.Controllers
{
    public class NPIBuyingController : Controller
    {
        // GET: NPIBuying
        public ActionResult Index(string stationCode,DateTime buyingDate)
        {
            if (buyingDate == null)
                ViewBag.BuyingDate = DateTime.Now.ToString("yyyy-MM-dd");
            else
                ViewBag.BuyingDate = buyingDate.ToString("yyyy-MM-dd");

            ViewBag.Station = BusinessLayerService.BuyingStationBL().GetSingle(stationCode);
            ViewBag.StationList = BusinessLayerService.BuyingStationBL().GetByArea("4");
            
            return View(BusinessLayerService.BuyingBL()
                .GetByNPIStation(stationCode, buyingDate));
        }
    }
}

FCVBuyingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FCV Buying System</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    @*<style>
            html {
                zoom: 80%;
            }
        </style>*@
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="~/Images/stec-bar.png" width="120" height="30" class="d-inline-block align-top" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="nav navbar-nav me-auto mb-2 mb-lg-0 text-white">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new { Area = "" }, null)">Home</a>
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Administrator
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Role", new { Area = "" }, null)">User</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "User", new { Area = "" }, null)">Role</a></li>
                            </ul>
                            @*<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Role", new { Area = "" }, null)">Roles</a></li>
                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "User", new { Area = "" }, null)">Users</a></li>
                                </ul>*@
                        </li>
                    }
                        @if (Request.IsAuthenticated && (User.IsInRole("Buyer") || User.IsInRole("Admin")))
                        {
                            <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "BuyingDocuments", new { Area = "" }, null)">Tepawong</a></li>
                            <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "NPIBuying", new { @stationCode = "", @buyingDate = @DateTime.Now.ToString("yyyy-MM-dd") })">NPI Daily Report</a></li>
                        }
                    </ul>
                    @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
                </div>
            </div>
        </nav>

        <div class="container mt-4">
            @RenderBody()
            <footer class="pt-3 mt-4 text-body-secondary border-top">
                <p>&copy; @DateTime.Now.Year - STEC FCV Web Application. Icons by <a href="https://icons8.com/">Icons8.</a></p>
            </footer>
        </div>
        @RenderSection("scripts", required: false)
    </body>
</html>